### ISSUE TITLE
[RFC #0090] - Intro video

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/rfcs#255]
[RFC #0090](https://github.com/buildpacks/rfcs/blob/main/text/0090-intro-video-script.md) - Intro video

Documentation:
- [ ] https://github.com/buildpacks/docs/issues/TBD

Video URLs:
- [ ] buildpacks.io
- [ ] Youtube

**Comment by samj1912** [comment]
Can what we currently have on the homepage be considered intro videos? https://buildpacks.io/

**Comment by natalieparellano** [comment]
This is true. I guess the intent here is to show that this particular intro video was planned but not made. If we want we can update the RFC status to be `On Hold` or `Superseded` and close it out.

**Comment by AidanDelaney** [comment]
We have a set of intro videos.  We can extend these, but I think this RFC is complete, so there's no need to keep it open.
