### ISSUE TITLE
[RFC #0115] - Rebase by Image Digest Reference

### ISSUE THREAD

**Issue by jabrown85** [buildpacks/rfcs#269]
[RFC #262](https://github.com/buildpacks/rfcs/blob/main/text/0115-rebase-immutable-image-ref.md) - Rebase by Image Digest Reference

Lifecycle:
- [x] https://github.com/buildpacks/lifecycle/issues/983
- [x] Released in lifecycle version `0.16.0`

**Maintainers**: when closing this issue as completed, submit a PR to update the `Status` of the RFC to `Implemented`.

**Comment by natalieparellano** [comment]
@jabrown85 would you mind doing this part: 
> when closing this issue as completed, submit a PR to update the Status of the RFC to Implemented
